db = [
("Agua",1.20),("Agua Mineral",1.00),("Baileys",3.00),("Baileys",3.19),
("Batido",2.50),("Batido",2.30),("Batidos naturales",3.50),("Botellin",1.40),
("Cafe + Croissant",2.50),("Cafe + Croissant o sandwich mixto",3.30),
("Cafe + Croissant plancha",2.70),("Cafe + Croissant plancha + zumo",3.60),
("Cafe + Tostada de mantequilla y mermeada",2.50),
("Cafe + Tostada de mantequilla y mermelada + zumo",3.30),
("Cafe + Tostada de tomate",2.50),("Cafe + Tostada de tomate + zumo",3.30),
("Cafe bombon",2.00),("Cafe con hielo",1.40),("Cafe con leche",1.40),
("Cafe Americano",1.50),("Cafe Bombon",2.00),("Cafe Cortado",1.40),
("Cafe Cortado",1.50),("Cafe Solo",1.40),("Cafe americano",1.40),
("Cafe con Leche",1.50),("Capuccino",2.00),("Capuchino",1.90),
("Carajillo",2.00),("Carajillo",2.00),("Cerveza Artesanal",2.70),
("Chipito licor",1.20),("Chupito",1.29),("Colacao + Croissant",2.50),
("Colacao + Croissant o sandwich mixto",3.30),("Colacao + Croissant plancha",2.70),
("Colacao + Tostada de mantequilla y mermelada",2.70),
("Colacao + Tostada de tomate",2.70),("Colacao/ Nesquik",1.60),
("Combinado",5.00),("Complementa tu desayuno con zumo",1.20),
("Copa Licor",2.70),("Copa Soberano",2.40),("Copa Whisky",3.61),
("Copa grande",5.50),("Copa grande",5.50),("Copa licor",2.50),
("Copa pequena",4.50),("Copa pequena",4.50),("Copa soberano",2.50),
("Copa whisky",3.50),("Croissant Clasico",1.50),("Croissant Mixto",2.70),
("Croissant Plancha",1.71),("Croissant mixto",2.40),("Croissant nutella",2.00),
("Croissant plancha",1.50),("Cucurucho",2.20),
("Desayuno 1 - Cafe + Tostada mantequilla y mermelada",2.70),
("Desayuno 10 - Cola Cao + Croissant o sandwich mixto",0.00),
("Desayuno 2 - Cafe + Tostada tomate y aceite",0.00),
("Desayuno 3 - Cafe + Croissant",2.50),
("Desayuno 4 - Cafe + Croissant Plancha",0.00),
("Desayuno 5 - Cafe + Croissant o sandwich mixto",3.60),
("Desayuno 6 - Cola Cao + Tostada mantequilla y mermelada",0.00),
("Desayuno 7 - Cola Cao + Tostada tomate y aceite",2.90),
("Desayuno 8 - Cola Cao + Croissant",0.00),
("Desayuno 9 - Cola Cao + Croissant Plancha",2.90),
("Distinto",2.20),("Donut",1.32),("Goffre Especial",0.00),
("Goffre Irresistible",3.50),("Gofre",3.00),("Infusion",1.40),
("Infusion Clasica",1.50),("Infusion Premium",1.71),("Infusion premium",1.60),
("Martini",2.50),("Napolitana",2.00),("Palmera chocolate",2.00),
("Palmera chocolate o blanco",2.20),("Refresco",2.40),("Refrescos",2.20),
("Suplemento Zumo Natural",1.30),("Sandwich Atun",2.90),("Sandwich Mixto",2.70),
("Sandwich Vegetal",2.70),("Sandwich Vegetal (grande)",2.90),
("TPV - Linea libre (10% IVA)",0.00),("TPV - Linea libre (21% IVA)",0.00),
("Tarrina grande",3.75),("Tarrina grande",3.75),("Tarrina pequena",2.20),
("Tarrina pequena",2.20),("Tercio",2.00),("Tercio 1906",2.50),
("Tinto de Verano",1.50),("Tinto de verano",2.20),("Tortitas Dulces",2.50),
("Tortitas Nata",0.00),("Tortitas Variadas",0.00),("Tortitas con fruta",3.50),
("Tortitas con nata",2.50),("Tostada o mollete de salmon y alioli",3.50),
("Tostada o mollete guacamole",3.00),
("Tostada o mollete guacamole con jamon iberico",4.00),
("Tostada o mollete guacamole con salmon",3.50),
("Tostada o mollete iberico",3.50),
("Tostada o mollete mermelada y mantequilla",1.40),
("Tostada o mollete serrano",2.60),("Tostada o mollete tomate",1.40),
("Tostada o mollete york y queso",2.50),("Te Frio",2.50),("Te Rojo",1.50),
("Te Verde",1.50),("Te de Tila",1.71),("Te frio",2.20),("Vaso de leche",1.30),
("Zumo",2.20),("Zumo Natural",2.30),("sandwich mixto",2.40),
("sandwich vegetal",2.60),("sandwich vegetal con atun",2.60),
]
carta=[
("CAFE","Solo",1.50,False),("CAFE","Con leche",1.50,False),("CAFE","Cortado",1.50,False),
("CAFE","Americano",1.50,False),("CAFE","Bombon",2.00,False),("CAFE","Capuccino",1.90,False),
("CAFE","Carajillo",2.00,False),("CAFE","Vaso de leche",1.50,False),
("CAFE","Cola Cao / Nesquik",1.70,False),("CAFE","Chocolate",2.40,False),
("INFUSIONES","Infusion (manzanilla, poleo, tila, te verde/rojo)",1.50,False),
("INFUSIONES","Infusion premium",1.80,False),
("INFUSIONES","Te frio (limon, frutos bosque, roibos, melocoton, pina)",2.40,False),
("INFUSIONES","Te frio (menta, melon, mojito)",2.40,False),
("SUPLEMENTOS","Tarrina mermelada",0.30,True),("SUPLEMENTOS","Tarrina mantequilla",0.30,True),
("SUPLEMENTOS","Tarrina tomate",0.30,True),("SUPLEMENTOS","Tarrina aceite",0.30,True),
("DESAYUNOS","1 - Cafe + Tostada mantequilla y mermelada",2.70,True),
("DESAYUNOS","2 - Cafe + Tostada tomate y aceite",2.70,True),
("DESAYUNOS","3 - Cafe + Croissant",2.80,True),
("DESAYUNOS","4 - Cafe + Croissant a la plancha",2.80,True),
("DESAYUNOS","5 - Cafe + Croissant o sandwich mixto",3.60,True),
("DESAYUNOS","6 - Cola Cao + Tostada mantequilla y mermelada",3.10,True),
("DESAYUNOS","7 - Cola Cao + Tostada tomate y aceite",2.90,True),
("DESAYUNOS","8 - Cola Cao + Croissant",2.90,True),
("DESAYUNOS","9 - Cola Cao + Croissant a la plancha",2.90,True),
("DESAYUNOS","10 - Cola Cao + Croissant o sandwich mixto",3.90,True),
("BOLLERIA","Croissant",1.70,False),("BOLLERIA","Croissant nutella",2.50,False),
("BOLLERIA","Tortitas con sirope o nutella",2.70,False),("BOLLERIA","Tortitas con nata",2.70,False),
("BOLLERIA","Tortitas con sirope y nata",3.00,False),("BOLLERIA","Tortitas con sirope y helado",3.00,False),("BOLLERIA","Tortitas con sirope, nata y helado",3.50,False),
("BOLLERIA","Goffre con sirope o nutella",3.70,False),("BOLLERIA","Goffre con nata",3.70,False),
("BOLLERIA","Goffre con sirope y nata",4.00,False),("BOLLERIA","Goffre con sirope y helado",4.00,False),
("BOLLERIA","Goffre con sirope, nata y helado",4.50,False),("BOLLERIA","Donut Glace",1.50,False),
("BOLLERIA","Donut Chocolate",1.60,False),("BOLLERIA","Napolitana",1.90,False),
("BOLLERIA","Porcion bizcocho",2.90,False),("BOLLERIA","Porcion Tarta",3.60,False),
("BOLLERIA","Palmera chocolate pequena",1.40,False),("BOLLERIA","Palmera grande",2.80,False),
("TOSTADA / MOLLETE","Mermelada y mantequilla",1.90,False),("TOSTADA / MOLLETE","Tomate y aceite",1.90,False),
("TOSTADA / MOLLETE","Serrano con tomate",3.10,False),("TOSTADA / MOLLETE","Iberico con tomate",4.20,False),
("TOSTADA / MOLLETE","York y queso",3.00,False),("TOSTADA / MOLLETE","Atun, tomate y mahonesa",3.10,False),
("TOSTADA / MOLLETE","Guacamole",3.40,False),("TOSTADA / MOLLETE","Guacamole con salmon",4.60,False),
("TOSTADA / MOLLETE","Guacamole con jamon iberico",4.60,False),("TOSTADA / MOLLETE","Salmon y alioli",4.20,False),
("CROISSANT / SANDWICH","Croissant plancha",1.90,False),("CROISSANT / SANDWICH","Croissant mixto",3.00,False),
("CROISSANT / SANDWICH","Sandwich mixto",3.00,True),("CROISSANT / SANDWICH","Sandwich vegetal",3.10,True),
("CROISSANT / SANDWICH","Sandwich vegetal con atun",3.40,False),
("BEBIDAS","Refrescos",2.50,True),("BEBIDAS","Zumos",2.50,True),("BEBIDAS","Agua mineral",1.00,False),
("BEBIDAS","Tinto de verano",2.50,False),("BEBIDAS","Botellin",1.50,True),("BEBIDAS","Tercio",2.50,False),
("BEBIDAS","Cerveza 1906",2.90,False),("BEBIDAS","Alhambra",2.90,False),
("BEBIDAS","Botellin sin gluten",1.70,False),("BEBIDAS","Batido chocolate",2.50,False),
("LICORES","Martini",3.00,True),("LICORES","Baileys",3.50,True),("LICORES","Copa licor",2.90,True),
("LICORES","Chupitos",1.60,True),("LICORES","Combinados",5.00,True),("LICORES","Copa Whisky",3.60,False),
("LICORES","Copa Soberano",2.50,False),("LICORES","Copa Castellana",2.50,True),
]
